### ISSUE TITLE
Missing references

### ISSUE THREAD

**Issue by Birusama** [Voidware-Prohibited/ALSXT#10]
There are casts to a missing B_PlayerController in B_ALSX_CameraManager and WB_ALS_HUD.

B_ALSXT_Character in Update Footprints State the ALSXFootprintStatePhase has a red pin for Foot Physical Material. (Probably intended for Surface Type, though compiles without complaint and it is unhooked to the branch/I guess unneeded.)

I believe these are things from ALS-Refactored-EOS. Not a problem to just erase and skip those parts, but mentioning them.

**Comment by colorindarkness** [comment]
Thank you. Sorry I didn't get this notification. I'm going through now and refactoring everything into components and cleaning up invalid references

**Comment by colorindarkness** [comment]
Fixed in [c91cb12](https://github.com/Voidware-Prohibited/ALSXT/commit/c91cb128429f037150ab93c6fc385d1b4a95e68f)
