### ISSUE TITLE
Mantle animations point to ALS-Refactored animations

### ISSUE THREAD

**Issue by Birusama** [Voidware-Prohibited/ALSXT#11]
I noticed the footprint decals were the old ones from ALS-Refactored as I was mantling; I checked, and it's pointing to the mantle data assets from ALS-Refactored.

Since there were already modified copies of the animations in ALSXT, I pointed to those montages; I found that the montages were pointing to the ASL-Refactored animation sequences. This was ultimately corrected by duplicating the mantle data assets, pointing them to the ALSXT montages, and modifying the ALSXT montages to point to the ALSXT animation sequences.

**Comment by colorindarkness** [comment]
Oh yes thank you, I do believe I missed replacing a couple montage references. I will make note to to that next!

**Comment by colorindarkness** [comment]
Fixed in [7369a9d](https://github.com/Voidware-Prohibited/ALSXT/commit/7369a9dde021b8e7c90d4ac7ffdf8629462b01fc)
