### ISSUE TITLE
Minor discrepancy: PrimaryInteraction input

### ISSUE THREAD

**Issue by Birusama** [Voidware-Prohibited/ALSXT#12]
I noticed the PrimaryInteraction input is set to IA_PrimaryAction instead of IA_PrimaryInteraction.

![image](https://user-images.githubusercontent.com/87715636/194395991-e87734a8-ae31-41d8-9bf3-af3c435c1375.png)

**Comment by colorindarkness** [comment]
Fixed in [f4a85c8](https://github.com/Voidware-Prohibited/ALSXT/commit/f4a85c80d68873c591a9c9f07841525270a8ed5b)
