### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by bojank** [Voidware-Prohibited/ALSXT#20]
I created a blank new project with ALSRefactored and ALSXT in the plugins folder, copied the configs from ALSRefactoed, the Refactored character works and i am able to move around but the ALSXT one does not respond except the what seems like a block action. I belive Left ALT. I was wondering if you can push me in the right direction to get it working

**Comment by bojank** [comment]
The original inputs from ALS-Refactored where missing.

**Comment by colorindarkness** [comment]
Thank you for letting me know! I'll address this next.

**Comment by Amorill-21** [comment]
I'm running into the same issue I believe, what did you do to resolve it?

**Comment by chakibchemso** [comment]
me too is there a quick fix

**Comment by bojank** [comment]
Inside ALSXT you need to add all the input actions as they are blank, then you need to edit the alsxt input context to add all those

**Comment by CybotDNA** [comment]
> Inside ALSXT you need to add all the input actions as they are blank, then you need to edit the alsxt input context to add all those

Hi, of course I have the same problem. Thank you for your solution! 
Can you maybe take a screenshot of an example fix so I can understand what I need to do? 

Test it in a blank project and installed the standard "Advanced Locomotion System Refactored" and it works. 

With the slides would of course be really awesome :-)

BR

**Comment by colorindarkness** [comment]
Hey everyone. I hope to have this fixed sometime during down time during the holidays!

**Comment by Um1aut** [comment]
But how to make it at by yourself? When the solution is not so complicated, what's the problem to tell us about it?

**Comment by colorindarkness** [comment]
> 

Bojank would need to submit a new PR, as I cannot see the changes he made in the Blueprints, which conflict with newer versions of files.

**Comment by colorindarkness** [comment]
Should now be fixed
