### ISSUE TITLE
Cant use duplicated character

### ISSUE THREAD

**Issue by bojank** [Voidware-Prohibited/ALSXT#22]
1) Duplicate ASLXT character
2) Switch gamemode character to duplicated
3) Dont work as intended

**Comment by colorindarkness** [comment]
Should be fixed in [81d124db4e3ec39f575e1946c0ca78834c994d05](https://github.com/Voidware-Prohibited/ALSXT/commit/81d124db4e3ec39f575e1946c0ca78834c994d05)
