### ISSUE TITLE
The enanched input nodes are all set to none

### ISSUE THREAD

**Issue by MrGoatsy** [Voidware-Prohibited/ALSXT#26]
The controller fails to compile and the character and no keys being pressed are being registered out of the menu on the right.

![image](https://user-images.githubusercontent.com/9994607/218008496-bc718a36-7338-4e5b-9aa0-ceb2d3f0daa5.png)

**Comment by colorindarkness** [comment]
Hello! Have you pulled recently? 7742efa (Feb 5, 2023) Should have fixed this after ALS-Refactored changed the names of the Input Actions. If this is still not working, let me know and I'll investigate further

**Comment by MrGoatsy** [comment]
It was a new project.

**Comment by colorindarkness** [comment]
And you have ALS-Refactored and all it's dependencies installed and working first?

**Comment by MrGoatsy** [comment]
Yes.

**Comment by colorindarkness** [comment]
OK. This should be fixed now in the newest commit. I believe it may have been an LFS issue lol

**Comment by MrGoatsy** [comment]
What is LFS?

**Comment by colorindarkness** [comment]
Git Large File Storage. I don't think the new binary uasset was being pushed to the repo, so it was an old version

**Comment by MrGoatsy** [comment]
Oke, thanks for the explanation.

Offtopic: When do you think vaulting will be added?

**Comment by colorindarkness** [comment]
After I get SetMovementModeLocked() working in Actor Components, or some alternative, that will also work on AI Characters. I'm currently trying to figure that out in the UnarmedCombatComponent
