### ISSUE TITLE
Warning IsNull is deprecated

### ISSUE THREAD

**Issue by Maciek-Letowt** [Voidware-Prohibited/ALSXT#28]
When I build after cloning the repository, I get the following warning in JetBrains Rider 2022.3.2 :
`ALSXTAnimationInstance.cpp(14): [C4996] 'TObjectPtr<AALSXTCharacter>::IsNull': IsNull is deprecated, please use operator bool instead.  if (!MyObjectPtr) { ... } Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.`

**Comment by colorindarkness** [comment]
Thanks for that, it doesn't appear in Visual Studio Pro 2019. Fixed in 3e845e4edf879431a4a9d89ef1afe4aa009217a9
