### ISSUE TITLE
Parameters & Settings not initialized properly log error on opening project

### ISSUE THREAD

**Issue by Maciek-Letowt** [Voidware-Prohibited/ALSXT#34]
Similar to closed bug [31](https://github.com/Voidware-Prohibited/ALSXT/issues/31)

My game project contains the ALSXT plugin. Errors are logged when I open my project in my IDE, and then in the Unreal Editor via my IDE.
My IDE is JetBrains Rider 2023.1

The errors have the following pattern:
`Error: ObjectProperty FALSXT...Parameters::Target is not initialized properly. Module:ALSXT File:Public/Settings/ALSXT...Settings.h`

There is no error building the project. 
There are no errors in the Message Log.
The live-coding recompile shows no errors.

However, when the Unreal Editor opens, the errors can be seen in the UE Output Log:

```
LogClass: Error: ObjectProperty FALSXTCombatParameters::Target is not initialized properly. Module:ALSXT File:Public/Settings/ALSXTCombatSettings.h
LogClass: Error: ObjectProperty FALSXTImpactReactionParameters::Target is not initialized properly. Module:ALSXT File:Public/Settings/ALSXTImpactReactionSettings.h
LogAutomationTest: Error: UObject.Class AttemptToFindUninitializedScriptStructMembers will be marked as failing due to errors being logged
LogAutomationTest: Error: LogClass: ObjectProperty FALSXTCombatParameters::Target is not initialized properly. Module:ALSXT File:Public/Settings/ALSXTCombatSettings.h
LogAutomationTest: Error: LogClass: ObjectProperty FALSXTImpactReactionParameters::Target is not initialized properly. Module:ALSXT File:Public/Settings/ALSXTImpactReactionSettings.h
```

**Comment by colorindarkness** [comment]
Hello! This issue should be resolved now!
