### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by Setmaster** [Voidware-Prohibited/ALSXT#42]
Getting this error
`  ALSXTCharacterSoundComponent.cpp(1575): [C2665] 'UGameplayStatics::SpawnSoundAttached': no overloaded function could convert all the argument types`

**Comment by jariktaurog** [comment]
I am having the same issue

**Comment by MrWilsonWilson** [comment]
Same error here

**Comment by MrWilsonWilson** [comment]
I deleted the function from cpp 1575 line and it built after that

**Comment by miketoupin** [comment]
I have exact same problem as @Setmaster above. Please note I am using the latest Unreal 5.3 version.

**Comment by Ender0920** [comment]
same issue~

**Comment by SAM-tak** [comment]
https://github.com/Voidware-Prohibited/ALSXT/pull/43
This may solve the issue.
