### ISSUE TITLE
Missing parenthesis in ALSXTCharacter.h

### ISSUE THREAD

**Issue by Mr4Goosey** [Voidware-Prohibited/ALSXT#67]
Compilation of ALSXT currently fails due to a missing parenthesis at the end of line 207 in ALSXTCharacter.h.
```
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "State|Als Character", Meta = (AllowPrivateAccess, Transient)
	FALSXTPoseState ALSXTPoseState;
```

**Comment by colorindarkness** [comment]
Oops! I don't know how that slipped by! Fixed in [f3d746b](https://github.com/Voidware-Prohibited/ALSXT/commit/f3d746b9acfbdecbb9d9a4a4b6bb611ed0eba309)
